version: "3.3"
services:
  anaconda:
    image: continuumio/anaconda3
    container_name: anaconda
    volumes:
    - ./notebooks:/opt/notebooks
    ports:
    - 16000:8888
    command: bash -c "conda install jupyterlab -y --quiet &&  mkdir -p /opt/notebooks && jupyter lab --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"